FROM hiromuhota/webspoon:0.8.0-base
MAINTAINER Hiromu Hota <hiromu.hota@hal.hitachi.com>
ARG base=8.0
ARG patch=13
ARG version=0.$base.$patch
ARG dist=8.0.0.0-28

COPY install.sh /tmp/install.sh
RUN sh /tmp/install.sh
