version: '3'
services:
  webspoon:
    image: hiromuhota/webspoon
    ports:
      - "8080:8080"
    volumes:
      - kettle:/home/tomcat/.kettle
      - pentaho:/home/tomcat/.pentaho
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
volumes:
  kettle:
  pentaho:
