version: '2'
services:
  webspoon:
    image: hiromuhota/webspoon:latest-full
    ports:
      - "8080:8080"
    volumes:
      - kettle:/root/.kettle
      - pentaho:/root/.pentaho
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
volumes:
  kettle:
  pentaho:
