FROM hiromuhota/webspoon:0.7.0-base
MAINTAINER Hiromu Hota <hiromu.hota@hal.hitachi.com>
ARG version=0.7.0.9
WORKDIR ${tomcat}
ADD https://github.com/HiromuHota/pentaho-kettle/releases/download/webspoon%2F$version/spoon.war ${tomcat}/webapps/
ADD https://github.com/HiromuHota/pdi-platform-utils-plugin/releases/download/webspoon%2F$version/pdi-platform-utils-plugin-7.0.0.0-25.jar ${tomcat}/plugins/platform-utils-plugin/
ADD https://github.com/HiromuHota/big-data-plugin/releases/download/webspoon%2F$version/pentaho-big-data-legacy-7.0.0.0-25.jar ${tomcat}/plugins/pentaho-big-data-plugin/
ADD https://github.com/HiromuHota/big-data-plugin/releases/download/webspoon%2F$version/pentaho-big-data-kettle-plugins-common-ui-7.0.0.0-25.jar ${tomcat}/system/karaf/system/pentaho/pentaho-big-data-kettle-plugins-common-ui/7.0.0.0-25/
ADD https://github.com/HiromuHota/pentaho-kettle/releases/download/webspoon%2F$version/repositories-plugin.jar ${tomcat}/system/karaf/system/pentaho-kettle/repositories-plugin/7.0.0.0-25/repositories-plugin-7.0.0.0-25.jar
