apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: webspoon
  name: webspoon
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webspoon
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: webspoon
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Xms1024m -Xmx2048m
        image: hiromuhota/webspoon
        imagePullPolicy: ""
        name: webspoon
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
