apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: webspoon
  name: webspoon
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    run: webspoon
status:
  loadBalancer: {}
